'use strict';

/**
 * IBDP Economics glossary
 * key: lookup key (lower-case English); en: display name; aliases: alternative English spellings
 * The front end detects these words on screen and shows a hover tooltip.
 */

const TERMS = {
  /* ---------- macro measurement ---------- */
  'gdp': { en: 'Gross Domestic Product', cat: 'Measurement', def: 'The market value of all final goods and services produced within a country over a period. Nominal GDP uses current prices; real GDP uses constant base-year prices.' },
  'real gdp': { en: 'Real GDP', cat: 'Measurement', def: 'GDP adjusted for price changes, valued at base-year prices. It reflects changes in the volume of output and is the core measure of economic growth.' },
  'nominal gdp': { en: 'Nominal GDP', cat: 'Measurement', def: 'GDP measured at current market prices, not adjusted for inflation. Nominal GDP may rise simply because prices rose.' },
  'gdp per capita': { en: 'GDP per capita', cat: 'Measurement', def: 'GDP divided by population. Widely used to compare living standards, but it ignores income distribution, non-market activity and environmental costs.' },
  'gni': { en: 'Gross National Income', cat: 'Measurement', def: 'GDP plus net factor income earned by residents abroad. It measures the income of the nation rather than of the domestic territory, so it often reflects residents’ income better than GDP.' },
  'economic growth': { en: 'Economic growth', cat: 'Macro objectives', def: 'A sustained increase in real GDP or real GDP per capita. Short-run growth comes from rising AD; long-run growth comes from rising AS (productive capacity).' },
  'business cycle': { en: 'Business cycle', cat: 'Models', def: 'The fluctuation of economic activity around its long-run trend, with four phases: boom, recession, slump/depression and recovery.' },
  'recession': { en: 'Recession', cat: 'Models', def: 'Usually two consecutive quarters of negative real GDP growth, with rising unemployment and falling consumption and investment.' },
  'output gap': { en: 'Output gap', cat: 'Models', def: '(Actual GDP − potential GDP) ÷ potential GDP. A positive gap means overheating and rising inflationary pressure; a negative gap means idle resources and high unemployment.' },
  'potential gdp': { en: 'Potential GDP', cat: 'Models', def: 'The maximum output attainable with existing capital, labour and technology without accelerating inflation — the position of the LRAS curve.' },
  'hdi': { en: 'Human Development Index', cat: 'Welfare', def: 'A UNDP composite welfare index: the geometric mean of life expectancy at birth, education and GNI per capita, on a 0–1 scale.' },
  'happy planet index': { en: 'Happy Planet Index', cat: 'Welfare', def: 'A sustainable welfare index from the New Economics Foundation: wellbeing × life expectancy ÷ ecological footprint. It asks how much welfare is bought at what environmental cost.' },
  'gini coefficient': { en: 'Gini coefficient', cat: 'Equity', def: 'Derived from the area between the Lorenz curve and the line of perfect equality, ranging from 0 (perfect equality) to 1 (perfect inequality). A higher value means a more unequal income distribution.' },
  'lorenz curve': { en: 'Lorenz curve', cat: 'Equity', def: 'A curve plotting the cumulative share of population against the cumulative share of income. The further it sits from the 45° equality line, the more unequal the distribution.' },
  'multidimensional poverty index': { en: 'Multidimensional Poverty Index', cat: 'Equity', def: 'Measures poverty across three dimensions — health, education and living standards (ten indicators) — capturing deprivation beyond low income.' },
  'poverty line': { en: 'Poverty line', cat: 'Equity', def: 'The income level that defines absolute poverty; the World Bank international line is US$2.15 a day (2017 PPP).' },

  /* ---------- unemployment and inflation ---------- */
  'unemployment rate': { en: 'Unemployment rate', cat: 'Macro objectives', def: 'Number of unemployed ÷ labour force × 100%. The labour force is the employed plus those actively seeking work.' },
  'labour force': { en: 'Labour force', cat: 'Measurement', def: 'The employed plus the unemployed — that is, everyone with a job plus everyone looking for one.' },
  'structural unemployment': { en: 'Structural unemployment', cat: 'Unemployment', def: 'Long-term unemployment caused by structural change, new technology or skills mismatch. It cannot be removed by raising AD.' },
  'frictional unemployment': { en: 'Frictional unemployment', cat: 'Unemployment', def: 'Short-term unemployment while workers change jobs or enter the labour market. It exists in every economy.' },
  'cyclical unemployment': { en: 'Cyclical / demand-deficient unemployment', cat: 'Unemployment', def: 'Unemployment caused by insufficient aggregate demand. Typical of recessions, it can be reduced by expansionary AD policies.' },
  'seasonal unemployment': { en: 'Seasonal unemployment', cat: 'Unemployment', def: 'Unemployment arising when demand for labour fluctuates with the seasons, as in agriculture or tourism.' },
  'nairu': { en: 'NAIRU', cat: 'Unemployment', def: 'The non-accelerating inflation rate of unemployment: the lowest unemployment rate that does not cause inflation to accelerate, shown by the vertical long-run Phillips curve.' },
  'natural rate of unemployment': { en: 'Natural rate of unemployment', cat: 'Unemployment', def: 'The unemployment rate at long-run equilibrium, equal to frictional plus structural unemployment.' },
  'inflation': { en: 'Inflation', cat: 'Macro objectives', def: 'A sustained rise in the general price level, usually measured by the annual change in the CPI or the GDP deflator. It erodes purchasing power and creates uncertainty.' },
  'deflation': { en: 'Deflation', cat: 'Macro objectives', def: 'A sustained fall in the general price level. It raises real interest rates and depresses consumption and investment, risking a debt–deflation spiral.' },
  'disinflation': { en: 'Disinflation', cat: 'Macro objectives', def: 'A falling inflation rate that is still positive — different from deflation, where prices actually fall.' },
  'hyperinflation': { en: 'Hyperinflation', cat: 'Macro objectives', def: 'Extremely rapid, uncontrolled inflation (commonly above 50% a month): the currency loses value and ceases to function as money.' },
  'cpi': { en: 'Consumer Price Index', cat: 'Measurement', def: 'Tracks the price of a fixed basket of consumer goods and services and is used to calculate the inflation rate.' },
  'demand-pull inflation': { en: 'Demand-pull inflation', cat: 'Inflation', def: 'Inflation caused by AD growing faster than AS (AD shifts right), usually alongside rising output and employment.' },
  'cost-push inflation': { en: 'Cost-push inflation', cat: 'Inflation', def: 'Inflation caused by higher factor costs (oil prices, wages) shifting SRAS left, with output falling and unemployment rising — stagflation.' },
  'stagflation': { en: 'Stagflation', cat: 'Inflation', def: 'Stagnation (high unemployment, low growth) combined with high inflation. It creates a policy dilemma: stimulus worsens inflation, restraint worsens unemployment.' },
  'phillips curve': { en: 'Phillips curve', cat: 'Models', def: 'Shows the trade-off between inflation and unemployment. The short-run curve slopes down; the long-run curve is vertical at the natural rate of unemployment.' },
  'expectations': { en: 'Expectations', cat: 'Concepts', def: 'How households and firms judge the future. Higher inflation expectations shift the SRPC up and weaken policy (expectations can be self-fulfilling).' },

  /* ---------- aggregate demand / supply ---------- */
  'aggregate demand': { en: 'Aggregate demand (AD)', cat: 'Models', def: 'Total planned spending in the economy at a given price level: AD = C + I + G + (X − M). The AD curve slopes down because a lower price level raises real wealth and real money balances and improves net exports.' },
  'aggregate supply': { en: 'Aggregate supply (AS)', cat: 'Models', def: 'The total output firms are willing to produce at a given price level. SRAS slopes up because wages and prices are sticky; LRAS is vertical at potential output.' },
  'sras': { en: 'Short-run aggregate supply', cat: 'Models', def: 'In the short run factor prices (especially wages) are rigid, so higher output raises unit costs: the curve slopes up and steepens as capacity limits approach.' },
  'lras': { en: 'Long-run aggregate supply', cat: 'Models', def: 'Once wages and prices have fully adjusted, output returns to the potential level, so the curve is vertical. Only supply-side improvements shift it right.' },
  'consumption': { en: 'Consumption', cat: 'Components', def: 'Household spending on goods and services, normally the largest component of GDP. It depends on disposable income, interest rates, taxes and confidence.' },
  'investment': { en: 'Investment', cat: 'Components', def: 'Firm spending on capital goods (plant, machinery, inventories). It depends on interest rates, business taxes, expected returns and confidence, and is the most volatile part of AD.' },
  'government spending': { en: 'Government spending', cat: 'Components', def: 'Government spending on public consumption and public investment — one of the main tools of fiscal policy.' },
  'net exports': { en: 'Net exports', cat: 'Components', def: 'Exports minus imports (X − M). Affected by foreign income, domestic income, the exchange rate, trade barriers and relative prices.' },
  'multiplier': { en: 'Multiplier', cat: 'Models', def: 'The ratio of the final change in national income to the initial change in spending: k = 1/(1 − MPC) in a simple two-sector model. One dollar of government spending generates k dollars of GDP.' },
  'marginal propensity to consume': { en: 'Marginal propensity to consume', cat: 'Models', def: 'The fraction of an extra unit of disposable income that is spent (MPC). MPC + MPS = 1, and a higher MPC means a larger multiplier.' },
  'accelerator': { en: 'Accelerator', cat: 'Models', def: 'The idea that output growth induces investment in proportion, making investment highly sensitive to growth — an important amplifier of economic fluctuations.' },
  'ad curve': { en: 'AD curve', cat: 'Models', def: 'The downward-sloping curve in the AD/AS diagram: a higher price level reduces real wealth, pushes up interest rates and weakens net exports, so the quantity demanded falls.' },

  /* ---------- fiscal policy ---------- */
  'fiscal policy': { en: 'Fiscal policy', cat: 'Demand management', def: 'Government policy that influences AD through spending and taxation. Expansionary policy (more spending / lower taxes) stimulates the economy; contractionary policy curbs inflation.' },
  'expansionary fiscal policy': { en: 'Expansionary fiscal policy', cat: 'Demand management', def: 'Higher government spending or lower taxes to raise AD, stimulating growth and cutting unemployment — but possibly worsening the budget balance, inflation and debt.' },
  'contractionary fiscal policy': { en: 'Contractionary fiscal policy', cat: 'Demand management', def: 'Lower government spending or higher taxes to reduce AD, used to curb inflation and improve the budget balance, but it may raise unemployment and slow growth.' },
  'direct tax': { en: 'Direct tax', cat: 'Fiscal tools', def: 'A tax levied directly on the income of individuals or firms, such as personal and corporate income tax. Progressive direct taxes improve income distribution.' },
  'indirect tax': { en: 'Indirect tax', cat: 'Fiscal tools', def: 'A tax on goods and services, such as VAT or sales tax. It raises prices and is regressive (a heavier burden on low-income households).' },
  'progressive tax': { en: 'Progressive tax', cat: 'Fiscal tools', def: 'A tax whose average rate rises with income, narrowing after-tax income differences.' },
  'regressive tax': { en: 'Regressive tax', cat: 'Fiscal tools', def: 'A tax that takes a larger share of income from the poor, such as a flat-rate indirect tax.' },
  'budget deficit': { en: 'Budget deficit', cat: 'Fiscal', def: 'Government spending exceeds revenue; the gap must be financed by borrowing.' },
  'budget surplus': { en: 'Budget surplus', cat: 'Fiscal', def: 'Government revenue exceeds spending; the surplus can repay debt or build up reserves.' },
  'government debt': { en: 'Government debt', cat: 'Fiscal', def: 'The stock of debt accumulated from past deficits, usually measured as a share of GDP. High debt raises interest costs, crowds out private investment and weakens crisis response.' },
  'crowding out': { en: 'Crowding out', cat: 'Fiscal', def: 'Government borrowing pushes up interest rates, reducing private investment and consumption and weakening expansionary fiscal policy.' },
  'automatic stabilisers': { en: 'Automatic stabilisers', cat: 'Fiscal', def: 'Mechanisms that work without new decisions: they raise spending (unemployment benefit) and cut taxes (progressive taxation) in a downturn, smoothing the cycle.' },
  'laffer curve': { en: 'Laffer curve', cat: 'Models', def: 'The relationship between tax revenue and the tax rate: revenue is zero at 0% and at 100%, with a revenue-maximising rate in between. Excessively high rates discourage work and investment and encourage evasion.' },
  'fiscal multiplier': { en: 'Fiscal multiplier', cat: 'Models', def: 'The change in GDP caused by a one-unit change in government spending. It is smaller in open economies because of the import leakage, and lower where taxes and debt are high.' },

  /* ---------- monetary policy ---------- */
  'monetary policy': { en: 'Monetary policy', cat: 'Demand management', def: 'Central bank policy that influences AD through interest rates, the money supply and credit conditions. Expansionary policy (rate cuts) stimulates; contractionary policy (rate rises) curbs inflation.' },
  'central bank': { en: 'Central bank', cat: 'Institutions', def: 'The institution that issues money, runs monetary policy and safeguards financial stability (e.g. the People’s Bank of China, the Federal Reserve, the State Bank of Viet Nam).' },
  'base rate': { en: 'Base / policy rate', cat: 'Monetary tools', def: 'The policy rate set by the central bank: the benchmark for commercial banks’ funding costs, and hence for market rates, investment and consumption.' },
  'interest rate': { en: 'Interest rate', cat: 'Monetary tools', def: 'The cost of borrowing and the reward for saving. The real interest rate = nominal rate − inflation, and it is the real rate that guides investment and saving decisions.' },
  'real interest rate': { en: 'Real interest rate', cat: 'Monetary tools', def: 'The nominal rate minus inflation. If the nominal rate is below inflation the real rate is negative, encouraging borrowing and discouraging saving.' },
  'required reserve ratio': { en: 'Required reserve ratio', cat: 'Monetary tools', def: 'The share of deposits banks must hold back. Raising it contracts credit and the money supply (contractionary); lowering it releases liquidity (expansionary).' },
  'open market operations': { en: 'Open market operations (OMO)', cat: 'Monetary tools', def: 'Central bank purchases and sales of government bonds on the secondary market to manage banking-system liquidity: buying injects money (expansionary), selling withdraws it (contractionary).' },
  'quantitative easing': { en: 'Quantitative easing (QE)', cat: 'Monetary tools', def: 'When rates are near zero and conventional tools fail, the central bank buys financial assets on a large scale to inject liquidity, push down long rates and support asset prices.' },
  'money supply': { en: 'Money supply', cat: 'Monetary tools', def: 'The total amount of money circulating in the economy. More money lowers rates and raises AD in the short run, but excessive long-run growth causes inflation.' },
  'transmission mechanism': { en: 'Transmission mechanism', cat: 'Concepts', def: 'The route by which monetary policy reaches the real economy: policy rate → market rates → investment/consumption/exchange rate → AD → output and prices. There are lags, typically 6–24 months.' },
  'liquidity trap': { en: 'Liquidity trap', cat: 'Concepts', def: 'A situation where rates are so low that further cuts do nothing: the public expects rates only to rise, so it holds money and monetary policy fails — fiscal policy must take over.' },
  'time lag': { en: 'Time lag', cat: 'Concepts', def: 'The delay between a policy being implemented and its effect (recognition, decision, implementation and impact lags) — one of the policymaker’s main difficulties.' },
  'monetary neutrality': { en: 'Monetary neutrality', cat: 'Concepts', def: 'In the long run, changes in the money supply affect only the price level, not real output: AD shifts right but only prices rise.' },

  /* ---------- supply-side policy ---------- */
  'supply-side policy': { en: 'Supply-side policy', cat: 'Supply side', def: 'Policy aimed at raising productive capacity so that LRAS shifts right, lowering inflation and raising growth at the same time. It comes in interventionist and market-based forms.' },
  'interventionist supply-side policy': { en: 'Interventionist supply-side policy', cat: 'Supply side', def: 'Government actively devotes resources to improving the quality and quantity of factors of production: education, health, infrastructure, R&D and industrial policy. Slow to work but targeted.' },
  'market-based supply-side policy': { en: 'Market-based supply-side policy', cat: 'Supply side', def: 'Policy that raises efficiency by reducing intervention and strengthening competition and incentives: privatisation, deregulation, labour market reform and tax cuts. Works faster but may worsen inequality.' },
  'investment in education and training': { en: 'Investment in education and training', cat: 'Supply side', def: 'Raises workers’ skills and human capital, lifting productivity and potential output in the long run and reducing structural unemployment.' },
  'infrastructure': { en: 'Infrastructure', cat: 'Supply side', def: 'Public capital such as transport, energy and communications. Better infrastructure lowers firms’ transport and transaction costs, raises productivity and attracts FDI.' },
  'research and development': { en: 'Research and development (R&D)', cat: 'Supply side', def: 'Spending on new technologies and processes that drives technical progress and long-run growth. It generates positive externalities, so it is often subsidised or protected by patents.' },
  'industrial policy': { en: 'Industrial policy', cat: 'Supply side', def: 'Selective government support for particular industries (infant industry protection, support for exporters, help for small firms) to upgrade the structure of the economy. It can distort resource allocation and invite rent-seeking.' },
  'privatisation': { en: 'Privatisation', cat: 'Market reforms', def: 'Selling or transferring state-owned enterprises to the private sector, raising efficiency through profit incentives and competition — but it can cause job losses, higher prices and asset-stripping.' },
  'deregulation': { en: 'Deregulation', cat: 'Market reforms', def: 'Cutting regulation and administrative approvals, lowering firms’ costs and promoting competition, at the risk of weaker safety, environmental or consumer protection.' },
  'trade liberalisation': { en: 'Trade liberalisation', cat: 'Market reforms', def: 'Removing or cutting tariffs and non-tariff barriers, widening markets, promoting competition and lowering costs — but it can hurt vulnerable domestic industries and workers.' },
  'labour market reform': { en: 'Labour market reform', cat: 'Market reforms', def: 'Weakening union power, lowering the minimum wage and unemployment benefits and reducing employment protection to make the labour market more flexible and cut the natural rate — but inequality and poverty may worsen.' },
  'minimum wage': { en: 'Minimum wage', cat: 'Labour market', def: 'A legally imposed wage floor. Moderate increases reduce in-work poverty and raise motivation; too high a floor causes unemployment (especially for unskilled workers) and cost-push inflation.' },
  'trade union power': { en: 'Trade union power', cat: 'Labour market', def: 'Unions’ ability to bargain collectively. Stronger unions mean higher wages and better conditions, but they can push up unit labour costs and reduce hiring.' },
  'unemployment benefit': { en: 'Unemployment benefit', cat: 'Labour market', def: 'Income support for the unemployed. It reduces poverty and supports consumption, but overly generous or long-lasting benefits can weaken job search incentives.' },
  'incentive-related policy': { en: 'Incentive-related policy', cat: 'Market reforms', def: 'Tax cuts (on income, capital gains and profits) that strengthen incentives to work, save, invest and innovate, raising potential output.' },

  /* ---------- equity and redistribution ---------- */
  'transfer payment': { en: 'Transfer payment', cat: 'Redistribution', def: 'A payment from government to individuals with no goods or services received in return (pensions, unemployment benefit, social assistance). It narrows income gaps and supports consumption.' },
  'direct provision': { en: 'Direct provision', cat: 'Redistribution', def: 'Government provides basic services such as education, health care and housing free or at subsidised prices, reducing poverty and building human capital.' },
  'subsidy': { en: 'Subsidy', cat: 'Redistribution', def: 'A payment by government to producers or consumers to lower prices, raise supply or encourage a particular activity. It creates deadweight loss and a fiscal burden.' },
  'universal basic income': { en: 'Universal Basic Income (UBI)', cat: 'Redistribution', def: 'A regular, unconditional cash payment of the same amount to every citizen. It simplifies welfare and reduces poverty, but it is costly and may weaken work incentives.' },
  'price ceiling': { en: 'Price ceiling', cat: 'Redistribution', def: 'A legally imposed maximum price below equilibrium, such as rent control. It causes shortages, queues and black markets.' },
  'price floor': { en: 'Price floor', cat: 'Redistribution', def: 'A legally imposed minimum price above equilibrium, such as a minimum wage or an agricultural support price. It causes surpluses.' },
  'anti-discrimination law': { en: 'Anti-discrimination law', cat: 'Redistribution', def: 'Law banning discrimination in employment and pay on grounds of gender, race, age and so on, raising the incomes of disadvantaged groups and improving distribution.' },
  'equity': { en: 'Equity', cat: 'Concepts', def: 'The fairness with which economic outcomes are distributed, divided into equality of opportunity and equality of outcome. It often trades off against efficiency.' },
  'kuznets curve': { en: 'Kuznets curve', cat: 'Models', def: 'The hypothesis that inequality first rises and then falls as an economy develops (an inverted U), with inequality peaking in mid-industrialisation.' },

  /* ---------- international economics ---------- */
  'international trade': { en: 'International trade', cat: 'International', def: 'The exchange of goods and services across borders, letting countries specialise according to comparative advantage and raising world output and welfare.' },
  'comparative advantage': { en: 'Comparative advantage', cat: 'International', def: 'When a country can produce a good at lower opportunity cost. Specialising and trading on this basis benefits both sides, even if one is absolutely more efficient at everything.' },
  'absolute advantage': { en: 'Absolute advantage', cat: 'International', def: 'Producing more output from the same resources. Absolute advantage is not required for trade — comparative advantage is.' },
  'terms of trade': { en: 'Terms of trade', cat: 'International', def: 'Export price index ÷ import price index × 100. A rise means the terms of trade improved: the same exports buy more imports.' },
  'balance of payments': { en: 'Balance of payments', cat: 'International', def: 'A systematic record of all economic transactions between a country and the rest of the world: the current account and the capital and financial accounts. In theory it always balances.' },
  'current account': { en: 'Current account', cat: 'International', def: 'Records net trade in goods and services plus primary and secondary income. A current account deficit must be financed by capital/financial account inflows.' },
  'trade balance': { en: 'Trade balance', cat: 'International', def: 'Exports of goods and services minus imports. A surplus means net exports are positive.' },
  'trade deficit': { en: 'Trade deficit', cat: 'International', def: 'Imports exceed exports. It may signal strong consumption or weak competitiveness — or strong domestic demand and an attractive investment climate.' },
  'trade surplus': { en: 'Trade surplus', cat: 'International', def: 'Exports exceed imports, so the country is accumulating foreign assets or reducing foreign liabilities.' },
  'exchange rate': { en: 'Exchange rate', cat: 'International', def: 'The rate at which one currency exchanges for another. Depreciation makes exports cheaper and imports dearer, improving net exports if the Marshall–Lerner condition holds.' },
  'appreciation': { en: 'Appreciation', cat: 'International', def: 'A rise in the value of the currency under floating rates. Exports become dearer and imports cheaper, usually reducing net exports and damping inflation.' },
  'depreciation': { en: 'Depreciation', cat: 'International', def: 'A fall in the value of the currency under floating rates. Exports become cheaper and imports dearer, improving net exports but raising imported inflation.' },
  'devaluation': { en: 'Devaluation', cat: 'International', def: 'An official cut in the value of the currency under fixed or managed exchange rates.' },
  'revaluation': { en: 'Revaluation', cat: 'International', def: 'An official increase in the value of the currency under fixed or managed exchange rates.' },
  'floating exchange rate': { en: 'Floating exchange rate', cat: 'Exchange rate regimes', def: 'The rate is set purely by market demand and supply with no government intervention: imbalances adjust automatically and monetary policy stays independent, but volatility raises uncertainty.' },
  'fixed exchange rate': { en: 'Fixed exchange rate', cat: 'Exchange rate regimes', def: 'The government pegs the rate and intervenes with reserves to hold it. It stabilises expectations and curbs inflation, but costs monetary independence and invites speculative attack.' },
  'managed exchange rate': { en: 'Managed float', cat: 'Exchange rate regimes', def: 'The rate is mostly market-determined, but the central bank buys and sells foreign exchange to smooth volatility or guide the level (a "dirty float").' },
  'foreign exchange reserves': { en: 'Foreign exchange reserves', cat: 'International', def: 'Foreign-currency assets held by the central bank to intervene in the market, service external debt and sustain confidence. Inadequate reserves invite a currency crisis.' },
  'marshall-lerner condition': { en: 'Marshall-Lerner condition', cat: 'Models', def: 'The condition for depreciation to improve the trade balance: the sum of the price elasticities of demand for exports and imports must exceed 1.' },
  'j-curve': { en: 'J-curve', cat: 'Models', def: 'After depreciation the trade balance first worsens (quantities adjust slowly) and then improves, tracing a path shaped like the letter J.' },
  'trade protection': { en: 'Trade protection', cat: 'Trade policy', def: 'Policy that restricts imports or supports exports through tariffs, quotas, subsidies and administrative barriers to protect domestic industry and jobs — at the cost of global efficiency and the risk of retaliation.' },
  'tariff': { en: 'Tariff', cat: 'Trade policy', def: 'A tax on imports. It raises import prices, protects domestic producers and raises government revenue, but hurts consumers and can trigger trade wars.' },
  'import quota': { en: 'Import quota', cat: 'Trade policy', def: 'A limit on the quantity of imports. Stricter than a tariff, it creates quota rents and can cause larger welfare losses.' },
  'export subsidy': { en: 'Export subsidy', cat: 'Trade policy', def: 'A payment to exporting firms that lowers their export price and raises competitiveness, but burdens the budget and can be challenged as unfair competition.' },
  'administrative barrier': { en: 'Administrative barrier', cat: 'Trade policy', def: 'A non-tariff barrier that restricts imports through cumbersome customs procedures, health and safety standards and other technical requirements.' },
  'import licensing': { en: 'Import licensing', cat: 'Trade policy', def: 'Requiring importers to obtain government permission, a non-tariff barrier whose quantity is directly controllable.' },
  'exchange control': { en: 'Exchange control', cat: 'Trade policy', def: 'Government limits on buying, selling and transferring foreign exchange (such as compulsory surrender or rationed access) to stabilise the rate and stop capital flight.' },
  'capital control': { en: 'Capital control', cat: 'Trade policy', def: 'Measures restricting cross-border capital flows. They reduce exchange rate and financial volatility, but also discourage inflows and financial deepening.' },
  'non-tariff barrier': { en: 'Non-tariff barrier (NTB)', cat: 'Trade policy', def: 'Trade restrictions other than tariffs: quotas, licences, technical standards, sanitary rules and administrative procedures.' },
  'dumping': { en: 'Dumping', cat: 'Trade policy', def: 'Exporting below the domestic price or below cost. It is unfair trade and the importing country may impose anti-dumping duties.' },
  'infant industry': { en: 'Infant industry', cat: 'Trade policy', def: 'A young industry that has not yet achieved scale or experience. Supporters argue for temporary protection until it matures.' },
  'trade war': { en: 'Trade war', cat: 'Trade policy', def: 'A tit-for-tat escalation of tariffs and retaliatory trade restrictions, usually cutting trade, raising prices and damaging growth on both sides.' },
  'economic integration': { en: 'Economic integration', cat: 'Integration', def: 'The progressive removal of barriers to trade and factor movements between countries, in several stages of increasing depth.' },
  'free trade area': { en: 'Free trade area', cat: 'Integration', def: 'Members remove tariffs and quotas among themselves but keep independent tariffs on non-members (e.g. USMCA, ASEAN).' },
  'customs union': { en: 'Customs union', cat: 'Integration', def: 'Members trade freely with each other and apply a common external tariff to non-members.' },
  'common market': { en: 'Common market', cat: 'Integration', def: 'A customs union that also allows free movement of factors of production such as labour and capital.' },
  'monetary union': { en: 'Monetary union', cat: 'Integration', def: 'Members share a single currency and a common central bank (e.g. the euro area), giving up national monetary policy and the exchange rate instrument.' },
  'trade creation': { en: 'Trade creation', cat: 'Integration', def: 'Integration shifts production from costly domestic sources to lower-cost partners, raising efficiency and welfare.' },
  'trade diversion': { en: 'Trade diversion', cat: 'Integration', def: 'Integration shifts imports from lower-cost non-members to higher-cost members because intra-bloc trade is tariff-free, possibly reducing welfare.' },
  'foreign direct investment': { en: 'Foreign direct investment (FDI)', cat: 'International', def: 'A foreign firm establishes or buys production facilities and manages them long term. It brings capital, technology, jobs and export capacity, but profits may flow out and the environment may suffer.' },
  'hot money': { en: 'Hot money', cat: 'International', def: 'Short-term capital that moves rapidly across borders chasing interest differentials and exchange rate gains, causing sharp swings in rates and asset prices.' },
  'sovereign risk': { en: 'Sovereign risk', cat: 'International', def: 'The risk that a government defaults or cannot service its debt, reflected in the risk premium on its bond yields and raising funding costs across the economy.' },
  'crowding in': { en: 'Crowding in', cat: 'Fiscal', def: 'The case where government investment in infrastructure and better expectations encourage additional private investment.' },
  'human capital': { en: 'Human capital', cat: 'Supply side', def: 'The skills, knowledge and health that workers possess — a key factor raising productivity and potential output.' },
  'productivity': { en: 'Productivity', cat: 'Supply side', def: 'Output per unit of input. Rising productivity is the fundamental source of higher long-run living standards.' },
  'ppp': { en: 'Purchasing power parity (PPP)', cat: 'International', def: 'Conversion at a rate adjusted for differences in price levels, used to compare incomes and output meaningfully across countries.' },
  'population growth': { en: 'Population growth', cat: 'Supply side', def: 'A larger population expands the labour force and total output, but if it outruns capital accumulation output per person may stagnate.' },
  'sustainable development': { en: 'Sustainable development', cat: 'Concepts', def: 'Development that meets present needs without compromising the ability of future generations to meet theirs, balancing the economic, social and environmental dimensions.' },
  'ecological footprint': { en: 'Ecological footprint', cat: 'Concepts', def: 'The biologically productive area needed to support a person’s or country’s consumption — a measure of environmental pressure.' },
  'circular flow of income': { en: 'Circular flow of income', cat: 'Models', def: 'A model of the flows of income and spending between households and firms; injections (I, G, X) and leakages (S, T, M) determine the level of national income.' },
  'injection': { en: 'Injection', cat: 'Models', def: 'Spending entering the circular flow: investment (I), government spending (G) and exports (X).' },
  'leakage': { en: 'Leakage / withdrawal', cat: 'Models', def: 'Income leaving the circular flow: saving (S), taxes (T) and imports (M).' },
  'keynesian multiplier': { en: 'Keynesian multiplier', cat: 'Models', def: 'ΔY = k × Δspending, where k = 1/(1 − MPC) or 1/(MPS + MPT + MPM): an initial spending change is magnified over several rounds.' }
};

/* Alias index (abbreviations and alternative spellings → key), for automatic term detection */
const ALIAS = {};
Object.keys(TERMS).forEach((k) => { ALIAS[TERMS[k].en.toLowerCase()] = k; });

const EXTRA_ALIAS = {
  'ad': 'aggregate demand', 'as': 'aggregate supply', 'srss': 'aggregate supply',
  'gdp': 'gdp', 'gni': 'gni', 'cpi': 'cpi', 'qe': 'quantitative easing', 'omo': 'open market operations',
  'vat': 'indirect tax', 'gst': 'indirect tax', 'r&d': 'research and development',
  'fdi': 'foreign direct investment', 'mpc': 'marginal propensity to consume',
  'hdi': 'hdi', 'hpi': 'happy planet index', 'mpi': 'multidimensional poverty index',
  'sme': 'industrial policy', 'firms': 'investment', 'workers': 'labour force',
  'living standards': 'real gdp', 'price stability': 'inflation', 'full employment': 'unemployment rate',
  'balance of trade': 'trade balance', 'trade barriers': 'trade protection',
  'currency union': 'monetary union', 'single market': 'common market',
  'debt': 'government debt', 'deficit': 'budget deficit', 'deflation': 'deflation',
  'recession': 'recession', 'boom': 'business cycle', 'recovery': 'business cycle'
};
Object.keys(EXTRA_ALIAS).forEach((a) => { ALIAS[a] = EXTRA_ALIAS[a]; });

module.exports = { TERMS, ALIAS, EXTRA_ALIAS };
